# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-09-26 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sorat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(max_length=100)),
                ('sorat_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_g_id', models.IntegerField(max_length=100)),
                ('v_lid', models.IntegerField(max_length=100)),
                ('v_text', models.TextField(max_length=10000)),
                ('v_d_text', models.TextField(max_length=10000)),
                ('v_sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.Sorat')),
            ],
        ),
    ]
