# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-09-26 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorat',
            name='sid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='verse',
            name='v_g_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='verse',
            name='v_lid',
            field=models.IntegerField(),
        ),
    ]
