# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-09-26 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_auto_20200926_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='v_d_text',
            field=models.TextField(default=models.TextField(max_length=10000), max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='verse',
            name='v_g_id',
            field=models.IntegerField(null=True),
        ),
    ]
