# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-09-27 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0005_auto_20200927_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verse',
            name='chars_count',
        ),
        migrations.RemoveField(
            model_name='verse',
            name='v_d_text',
        ),
        migrations.RemoveField(
            model_name='verse',
            name='v_g_id',
        ),
        migrations.RemoveField(
            model_name='verse',
            name='v_lid',
        ),
        migrations.RemoveField(
            model_name='verse',
            name='v_sid',
        ),
        migrations.RemoveField(
            model_name='verse',
            name='v_text',
        ),
    ]
