# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-09-27 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0006_auto_20200927_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='chars_count',
            field=models.TextField(default="{'ا': 0, 'ب': 0, 'ج': 0, 'د': 0, 'ه': 0, 'و': 0, 'ز': 0, 'ح': 0, 'ط': 0, 'ي': 0, 'ك': 0, 'ل': 0, 'م': 0, 'ن': 0, 'س': 0, 'ع': 0, 'ف': 0, 'ص': 0, 'ق': 0, 'ر': 0, 'ش': 0, 'ت': 0, 'ث': 0, 'خ': 0, 'ذ': 0, 'ض': 0, 'ظ': 0, 'غ': 0, 'أ': 0, 'ء': 0, 'ئ': 0, 'ى': 0, 'ؤ': 0, ' ': 0, 'ة': 0}", max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='verse',
            name='v_d_text',
            field=models.TextField(default='', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='verse',
            name='v_g_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='verse',
            name='v_lid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verse',
            name='v_sid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quran.Sorat'),
        ),
        migrations.AddField(
            model_name='verse',
            name='v_text',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
