# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-09-27 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0007_auto_20200927_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='v_sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.Sorat'),
        ),
    ]
