# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-09-27 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0008_auto_20200927_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='chars_count',
            field=models.TextField(default={' ': 0, 'ء': 0, 'أ': 0, 'ؤ': 0, 'ئ': 0, 'ا': 0, 'ب': 0, 'ة': 0, 'ت': 0, 'ث': 0, 'ج': 0, 'ح': 0, 'خ': 0, 'د': 0, 'ذ': 0, 'ر': 0, 'ز': 0, 'س': 0, 'ش': 0, 'ص': 0, 'ض': 0, 'ط': 0, 'ظ': 0, 'ع': 0, 'غ': 0, 'ف': 0, 'ق': 0, 'ك': 0, 'ل': 0, 'م': 0, 'ن': 0, 'ه': 0, 'و': 0, 'ى': 0, 'ي': 0}, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='verse',
            name='v_text',
            field=models.TextField(default='', max_length=10000, null=True),
        ),
    ]
