# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-09-27 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0009_auto_20200927_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='v_g_id',
            field=models.IntegerField(default=0),
        ),
    ]
