# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-09-27 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0012_auto_20200927_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='v_words_count',
            field=models.IntegerField(default=0, max_length=100, null=True),
        ),
    ]
