# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-09-27 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0013_verse_v_words_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='v_words_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
