# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-09-27 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0014_auto_20200927_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='v_joumla_sum',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
