# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-09-27 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0017_auto_20200927_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='v_words',
            field=models.CharField(default='', max_length=10000, null=True),
        ),
    ]
