# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-09-27 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0018_verse_v_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='v_w_max_rpt',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
