# Generated by Django 3.0.3 on 2020-10-03 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0020_auto_20201002_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sorat', models.ForeignKey(help_text='Sorat', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quran.Sorat')),
                ('verse', models.ForeignKey(help_text='Verse', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quran.Verse')),
            ],
        ),
    ]
