# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-10-05 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0022_auto_20201005_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quran',
            name='sorat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quran.Sorat'),
        ),
    ]
